# Generated by Django 3.1.2 on 2021-06-10 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('gold', 'gold'), ('silver', 'silver'), ('Bronze', 'Bronze'), ('none', 'none')], default='none', max_length=50)),
                ('money', models.IntegerField(blank=True, default=0, null=True)),
                ('last_buy', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercoins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
