# Generated by Django 3.1.2 on 2021-06-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='rank',
            field=models.CharField(choices=[('gold', 'gold'), ('silver', 'silver'), ('bronze', 'bronze'), ('none', 'none')], default='none', max_length=50),
        ),
    ]
