# Generated by Django 3.1.7 on 2021-06-29 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210612_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userwalllet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
