# Generated by Django 3.1.2 on 2021-06-10 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_specialitem'),
        ('users', '0003_auto_20210610_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingWithCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coinshop', to='users.coins')),
                ('special_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Specialitemforbuy', to='items.specialitem')),
            ],
        ),
    ]
