# Generated by Django 3.1.2 on 2021-04-11 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('description', models.TextField(blank=True)),
                ('manufacture_Data', models.DateField()),
                ('Expiration_Data', models.DateField()),
                ('count', models.IntegerField(blank=True, default=0)),
                ('onlineShop', models.BooleanField(blank=True, default=True)),
                ('shopID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
