# Generated by Django 3.1.2 on 2021-04-26 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('description', models.TextField(blank=True)),
                ('manufacture_Date', models.DateField(blank=True)),
                ('Expiration_Date', models.DateField(blank=True)),
                ('count', models.IntegerField(blank=True, default=0)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('discount', models.IntegerField(blank=True, default=0)),
                ('category', models.CharField(choices=[('Spices and condiments and food side dishes', 'Spices and condiments and food side dishes'), ('Cosmetics', 'Cosmetics'), ('Makeup and trimming', 'Makeup and trimming'), ('Protein', 'Protein'), ('Junk Food', 'Junk Food'), ('Nuts', 'Nuts'), ('Sweets and desserts', 'Sweets and desserts'), ('perfume', 'perfume'), ('Fruits and vegetables', 'Fruits and vegetables'), ('Dairy', 'Dairy'), ('Drinks', 'Drinks'), ('Washing and Cleaning Equipment', 'Washing and Cleaning Equipment'), ('others', 'others')], default='others', max_length=50)),
                ('shopID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopid', to='shops.shop')),
            ],
        ),
    ]
