# Generated by Django 3.1.2 on 2021-04-11 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='Expiration_Data',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacture_Data',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='shopID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopid', to='shops.shop'),
        ),
    ]
