# Generated by Django 3.1.2 on 2021-04-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210411_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Expiration_Data',
            new_name='Expiration_Date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='manufacture_Data',
            new_name='manufacture_Date',
        ),
    ]
