# Generated by Django 3.1.2 on 2021-04-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210411_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Spices and condiments and food side dishes', 'Spices and condiments and food side dishes'), ('Cosmetics', 'Cosmetics'), ('Makeup and trimming', 'Makeup and trimming'), ('Protein', 'Protein'), ('Junk Food', 'Junk Food'), ('Nuts', 'Nuts'), ('Sweets and desserts', 'Sweets and desserts'), ('perfume', 'perfume'), ('Fruits and vegetables', 'Fruits and vegetables'), ('Dairy', 'Dairy'), ('Drinks', 'Drinks'), ('Makeup and trimming', 'Makeup and trimming'), ('Washing and Cleaning Equipment', 'Washing and Cleaning Equipment'), ('otherst', 'others')], default='others', max_length=50),
        ),
    ]
