# Generated by Django 3.1.7 on 2021-06-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210521_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_with_discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
