# Generated by Django 3.1.2 on 2021-06-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_price_with_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='specialitems/')),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(blank=True, default=200)),
            ],
        ),
    ]
