# Generated by Django 3.1.7 on 2021-05-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_price_with_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='onlineShop',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
