# Generated by Django 3.1.2 on 2021-06-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_specialitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='items/qr_codes/'),
        ),
    ]
