# Generated by Django 3.1.7 on 2021-03-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='image/')),
                ('address', models.CharField(max_length=500)),
                ('theme', models.IntegerField(blank=True, default=1, null=True)),
                ('shomare_sabt', models.IntegerField(blank=True, default=1, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
