<<<<<<< HEAD
# Generated by Django 3.1.7 on 2021-04-02 15:17
=======
# Generated by Django 3.1.7 on 2021-03-31 12:32
>>>>>>> feature/v1.0.0/login-signup-back

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=200)),
<<<<<<< HEAD
                ('logo', models.ImageField(blank=True, null=True, upload_to='image/')),
=======
                ('logo', models.ImageField(blank=True, upload_to='image/')),
>>>>>>> feature/v1.0.0/login-signup-back
                ('address', models.CharField(max_length=500)),
                ('theme', models.IntegerField(blank=True, default=1, null=True)),
                ('shomare_sabt', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
<<<<<<< HEAD
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_shop', to=settings.AUTH_USER_MODEL)),
=======
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shop', to=settings.AUTH_USER_MODEL)),
>>>>>>> feature/v1.0.0/login-signup-back
            ],
        ),
    ]
