# Generated by Django 3.1.7 on 2021-04-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20210411_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='online',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
