# Generated by Django 3.1.7 on 2021-06-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='wallet_boolean',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
