# Generated by Django 3.1.7 on 2021-06-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppings', '0003_shoppingitem_sum_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='wallet_boolean',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
